### ISSUE TITLE
高级管理员不能编辑其它用户的文档

### ISSUE THREAD

**Issue by gao88** [lifei6671/godoc#12]

**Comment by lifei6671** [comment]
是的，高级管理员只能修改项目信息，不能编译文档。

**Comment by gao88** [comment]
还有一个问题，就是一个文档只能一个用户编辑，不能有多个用户编辑，这个挺麻烦的

**Comment by lifei6671** [comment]
@gao88 可以由多个用户编辑啊。只要添加成员就行了。

**Comment by naokij** [comment]
@lifei6671 我现在把公司旧知识库的内容转入到新知识库，但是毕竟内容很多，一个人无法全部完成。所以我用admin账号创建项目，然后给新开的普通账号项目权限，但是一个一个这样做会比较麻烦。在现有的权限框架下，有没有比较简单的做法？

或者，换一种思考方式，允许管理员编辑所有的项目，这样知识库准备阶段先开设多个管理员，全部编辑好之后，再调整管理员用户权限为普通用户？

**Comment by lifei6671** [comment]
@naokij 普通管理员是可以编辑所有项目的，只不过是目前v0.2版本没有开放。下个版本会开放普通管理员也可以进管理后台。
如果是在v0.2版本上的话，可以手动更改数据库用户的角色。

**Comment by naokij** [comment]
@lifei6671 我刚才测试了最新dev分支上的版本，管理员无法编辑admin创建的项目。

**Comment by lifei6671** [comment]
@naokij 刚刚修改了编辑权限，现在dev分支应该可以了。

**Comment by naokij** [comment]
谢谢，已经看到了
