### ISSUE TITLE
升级godoc时，把我之前的mysql全部给删除了，唉

### ISSUE THREAD

**Issue by gao88** [lifei6671/godoc#16]

**Comment by lifei6671** [comment]
覆盖升级不能删除install.lock文件，这个文件是用来标识是否安装过。如果删了，会自动再初始化一次数据库。

**Comment by wolcengit** [comment]
使用容器也悲剧了，测试就没有没有去挂载卷，每次都被重新初始化，是否可以依据数据库中表格是否存在，表格中数据是否存在来判断是否需要初始化呢？

**Comment by lifei6671** [comment]
@wolcengit 新版会去掉自动初始化数据库的功能，改为手动初始化。
