### ISSUE TITLE
文章的保存与发布

### ISSUE THREAD

**Issue by naokij** [lifei6671/godoc#18]
对这两个功能有点不明白：
文章修改的内容必须保存并且发布之后，才会在阅读那边看到，为何不做成点发布以后，就直接自动保存+发布，这样可以省去一次操作。又或者干脆两个功能合并在一起，保存发布一次完成？

**Comment by lifei6671** [comment]
因为有些人可能一次性没有编辑完文档，需要有时间再编辑。所以两个功能分开了。
还有一种情况，我想将整个项目中所有文档维护完毕才让前台看到。

**Comment by gao88** [comment]
如果把git做为数据库就好了

**Comment by lifei6671** [comment]
@gao88 当时考虑过这个问题。后来想，可能用这个程序的不一定都是程序员。

**Comment by naokij** [comment]
@lifei6671 那这样把发布的功能改成保存+发布，这样节省一次操作会比较方便一些。

**Comment by lifei6671** [comment]
@naokij
发布不是发布的一篇文章，是发布整个项目。
保存仅仅保存的是一篇文章。

**Comment by naokij** [comment]
@lifei6671 了解了，谢谢。
