### ISSUE TITLE
附件问题

### ISSUE THREAD

**Issue by gdlaoqiang** [lifei6671/godoc#22]
html编辑器下面没办法添加附件？好多东西都都要添加进去。比如音频一些软件文件啊。

**Comment by lifei6671** [comment]
html暂时没有实现附件功能。

**Comment by gdlaoqiang** [comment]
不科学啊。对了在插入地图时候，发布刷新浏览页面不会更新，要从新打开，从新打开有时候可以显示地图，有时候显示不了。动态地图更别提了空白

**Comment by lifei6671** [comment]
地图是编辑器自带的功能，新版本去掉了。因为这个功能依赖百度地图的密钥。而且有调用次数。

**Comment by qiankunshe** [comment]
可以加入配置项，让他自己配置 百度地图密钥呀
