### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by gdlaoqiang** [lifei6671/godoc#26]
登录随便输入无提示反馈。

**Comment by lifei6671** [comment]
你登录的哪个系统？你自己的还是Demo站上的？

**Comment by gdlaoqiang** [comment]
https://doc.iminho.me/login

**Comment by lifei6671** [comment]
是因为我开启了七牛的加速，但是没配置HTTPS证书。七牛的加速有问题，已经反馈给七牛了。
