### ISSUE TITLE
附件上传类型与大小

### ISSUE THREAD

**Issue by gdlaoqiang** [lifei6671/godoc#27]
如题

**Comment by lifei6671** [comment]
请详细描述问题细节。

**Comment by gdlaoqiang** [comment]
比如我添加压缩包提示不支持类型？
发现一个很超出寻常问题，就是阅读状态搜索应该字体加红才知道在哪里。还有在编辑状态怎么退出编辑状态呢？

**Comment by lifei6671** [comment]
1、上传文件支持的类型请在conf/app.conf中配置。
2、阅读搜索高亮暂时未实现。
3、编辑状态关闭浏览器就行了。

**Comment by gdlaoqiang** [comment]
分享了为什么还要登录呢？

**Comment by gdlaoqiang** [comment]
阅读还是有个回到顶部。这样不用滚动太多。

**Comment by lifei6671** [comment]
和文档公开状态有关，和是否开启匿名访问有关。

如果开启了匿名访问，并且文档又是公开状态，就不需要登录。
