### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by syouien** [lifei6671/godoc#28]
godoc/vendor/github.com/astaxie/beego/toolbox
godoc/vendor/github.com/bradfitz/gomemcache/memcache
godoc/vendor/github.com/astaxie/beego/session
godoc/vendor/github.com/go-sql-driver/mysql
godoc/vendor/github.com/garyburd/redigo/internal
godoc/vendor/github.com/garyburd/redigo/redis
github.com/lifei6671/godoc/vendor/github.com/astaxie/beego/config
godoc/vendor/github.com/astaxie/beego/context
godoc/vendor/github.com/astaxie/beego/session/memcache
github.com/lifei6671/godoc/vendor/github.com/astaxie/beego/utils
godoc/vendor/github.com/astaxie/beego/session/redis
godoc/vendor/github.com/astaxie/beego
github.com/lifei6671/godoc/vendor/github.com/astaxie/beego/grace
godoc/vendor/github.com/astaxie/beego/session/mysql
github.com/lifei6671/godoc/vendor/github.com/astaxie/beego/session
github.com/lifei6671/godoc/vendor/github.com/astaxie/beego/logs
github.com/lifei6671/godoc/vendor/github.com/astaxie/beego/toolbox
github.com/lifei6671/godoc/vendor/github.com/astaxie/beego/context
github.com/lifei6671/godoc/vendor/github.com/astaxie/beego/orm
github.com/lifei6671/godoc/vendor/golang.org/x/image/math/fixed
github.com/lifei6671/godoc/vendor/github.com/golang/freetype/raster
github.com/lifei6671/godoc/vendor/golang.org/x/image/font
github.com/lifei6671/godoc/vendor/github.com/astaxie/beego
github.com/lifei6671/godoc/vendor/github.com/golang/freetype/truetype
github.com/lifei6671/godoc/vendor/github.com/boombuler/barcode
github.com/lifei6671/godoc/vendor/github.com/boombuler/barcode/utils
github.com/lifei6671/godoc/vendor/github.com/boombuler/barcode/qr
github.com/lifei6671/godoc/vendor/github.com/golang/freetype
github.com/lifei6671/godoc/vendor/github.com/lifei6671/gocaptcha
github.com/lifei6671/godoc/vendor/github.com/nfnt/resize
github.com/lifei6671/godoc/utils/wkhtmltopdf
github.com/lifei6671/godoc/conf
github.com/lifei6671/godoc/graphics
github.com/lifei6671/godoc/utils
github.com/lifei6671/godoc/models
github.com/lifei6671/godoc/commands
github.com/lifei6671/godoc/controllers
github.com/lifei6671/godoc/routers
godoc
# godoc
./main.go:29: cannot use controllers.ErrorController literal (type *controllers.ErrorController) as type "godoc/vendor/github.com/astaxie/beego".ControllerInterface in argument to "godoc/vendor/github.com/astaxie/beego".ErrorController:
        *controllers.ErrorController does not implement "godoc/vendor/github.com/astaxie/beego".ControllerInterface (wrong type for Init method)
                have Init(*"github.com/lifei6671/godoc/vendor/github.com/astaxie/beego/context".Context, string, string, interface {})
                want Init(*"godoc/vendor/github.com/astaxie/beego/context".Context, string, string, interface {})

**Comment by lifei6671** [comment]
请检查本地是否存在低版本的beego源码。
