### ISSUE TITLE
针对V0.2    关于mindoc一点建议

### ISSUE THREAD

**Issue by JcQSteven** [lifei6671/godoc#30]
1、后台管理-项目管理
   可以增加添加项目，不然还要跑到个人项目管理去添加。感觉使用上不方便
2、超级管理员在仪表盘可以看所有文章的列表或者标题以及附件内容，而不是只是显示数目
3、在私有项目分配权限的时候添加用户应该采用列表选择或者分组选择，而不是手动输入用户名
4、添加用户分组功能

**Comment by lifei6671** [comment]
1、个人项目和项目管理是两个模块，不能混在一块的。
2、这个功能后期会开发。
3、因为考虑到用户太多，最好是按照用户名添加。后期会添加团队功能。
4、后期会增加团队功能，所以分组不是必须的了。

**Comment by JcQSteven** [comment]
谢谢
