### ISSUE TITLE
要是支持sqlite数据库就好了

### ISSUE THREAD

**Issue by xdeng** [lifei6671/godoc#32]
要是支持sqlite数据库就好了，小范围使用不想装MySQL这东东。

**Comment by lifei6671** [comment]
正在考虑是否支持。

**Comment by gdlaoqiang** [comment]
必须支持啊

**Comment by naokij** [comment]
尝试编译dev分支，sqlite3在mac上交叉编译很头疼啊

**Comment by lifei6671** [comment]
@naokij 嗯，sqlite用到了C代码，需要使用CGO编译，我的Windows电脑上编译成功了。没用过mac。
