### ISSUE TITLE
编辑页面，在左边目录名称右键选择添加文档，弹出来的仍然是“添加目录”对话框

### ISSUE THREAD

**Issue by chorylee** [lifei6671/godoc#33]
编辑页面，在左边目录名称右键选择添加文档，弹出来的仍然是“添加目录”对话框，这样就无法创建树形目录结构。

**Comment by chorylee** [comment]
@lifei6671 帮忙看一下，是不是右键的目标URL设置错了

**Comment by lifei6671** [comment]
目录就是文档，文档就是目录。

**Comment by chorylee** [comment]
那如何创建之前smartwiki那种树状导航结构呢？

**Comment by lifei6671** [comment]
文档下可以新建子文档。你不都会右键了吗？
