### ISSUE TITLE
本地跑不起来

### ISSUE THREAD

**Issue by mohong122** [lifei6671/godoc#36]
2017/05/23 10:11:39 SUCCESS  ▶ 0016 './godoc' is running...
./godoc flag redefined: graceful
panic: ./godoc flag redefined: graceful

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc0420381e0, 0xdfa6e0, 0xe54f55, 0xb0c8d0, 0x8, 0xb21c18, 0x21)
        C:/Go/src/flag/flag.go:793 +0x427
flag.BoolVar(0xe54f55, 0xb0c8d0, 0x8, 0x0, 0xb21c18, 0x21)
        C:/Go/src/flag/flag.go:572 +0x79
github.com/lifei6671/godoc/vendor/github.com/astaxie/beego/grace.init.1()
        C:/dev/golang/src/github.com/lifei6671/godoc/vendor/github.com/astaxie/beego/grace/grace.go:93 +0x67
github.com/lifei6671/godoc/vendor/github.com/astaxie/beego/grace.init()
        C:/dev/golang/src/github.com/lifei6671/godoc/vendor/github.com/astaxie/beego/grace/server.go:307 +0x90
github.com/lifei6671/godoc/vendor/github.com/astaxie/beego.init()
        C:/dev/golang/src/github.com/lifei6671/godoc/vendor/github.com/astaxie/beego/tree.go:581 +0x8e
github.com/lifei6671/godoc/conf.init()
        C:/dev/golang/src/github.com/lifei6671/godoc/conf/mail.go:38 +0x50
main.init()
        C:/dev/golang/src/godoc/main.go:35 +0x6e

**Comment by lifei6671** [comment]
你是自己编译的还是下载编译好的？

**Comment by mohong122** [comment]
@lifei6671 自己编译的，想在你这个基础上加个功能，但是没能跑成功

**Comment by lifei6671** [comment]
本地go的版本需要1.8以上，beego也需要1.8以上版本。

**Comment by mohong122** [comment]
![image](https://cloud.githubusercontent.com/assets/1935979/26336827/488dc9f4-3fa7-11e7-8fc0-2bb815815b68.png)
