### ISSUE TITLE
不支持多人编辑

### ISSUE THREAD

**Issue by Jerry9547** [lifei6671/godoc#37]
不能像项目分组一样公开的项目，项目组成员（身份为管理员的）都可以编辑同一个文档

**Comment by lifei6671** [comment]
项目可以添加成员。点击项目列表中的项目标题。

**Comment by gdlaoqiang** [comment]
编辑时候，返回上次连接，直接调错。

**Comment by lifei6671** [comment]
这不是错误，因为页面是异步加载的，你使用浏览器的回退功能，肯定加载的是json结构的数据。
