### ISSUE TITLE
希望在Markdown编辑器下可以直接粘贴上传图片

### ISSUE THREAD

**Issue by bliblimumu** [lifei6671/godoc#41]

**Comment by lifei6671** [comment]
编辑器作者没提供粘贴事件，我研究了下发现，能捕获粘贴事件，但是无法得到粘贴的内容。

**Comment by bliblimumu** [comment]
我看网上的教程有办法弄得http://www.cnblogs.com/honghongming/p/4494282.html

**Comment by bliblimumu** [comment]
作者能增加以下这个功能吗？

**Comment by lifei6671** [comment]
因为编辑器限制，暂时实现不了。我去编辑器作者的issue上看过，还没人实现过。
