### ISSUE TITLE
导出pdf中的图片资源问题

### ISSUE THREAD

**Issue by wienerxu** [lifei6671/godoc#42]
用wkhtmltopdf分页导出pdf功能很强大，但是文档中的图片没有导出。临时页面html文件在服务器cache目录下无法引用/uploads/目录下上传的图片。
wkhtmltopdf的命令中，如果把分页文件放在/uploads/目录下的临时文件夹，再加上 http://127.0.0.1:8181 前缀，应该可以访问上传的图片，不过导出时经过服务器请求静态页面。

**Comment by lifei6671** [comment]
确实没考虑到图片问题。

**Comment by lifei6671** [comment]
这一版本的图片问题，是简单的替换了<img src="/uploads 实现的，如果你的源码中存在非图片的类似代码可能会被替换掉。
