### ISSUE TITLE
pdf导出配置说明有点简单

### ISSUE THREAD

**Issue by vindell** [lifei6671/godoc#43]
不大明白 应该怎么去配置 这个wkhtmltopdf的参数； 我已经将wkhtmltox 解压到了linux的一个目录 ；然后呢；该如何去配置 ； 要注意什么；

**Comment by lifei6671** [comment]
wkhtmltopdf 的具体配置你需要看 wkhtmltopdf 官网的文档。

**Comment by vindell** [comment]
恩 在两台Linux主机 都安装了godoc 和 wkhtmltopdf ；一台正常（可导出PDF，文档错位乱码另说），一台不正常；不知道为什么，有时间再去深究
