### ISSUE TITLE
分享url显示localhost:8181

### ISSUE THREAD

**Issue by naokij** [lifei6671/godoc#44]
mindoc放在nginx后面，分享出来的网址会包含localhost:8181
还有编辑项目时候的“标识”也是同样问题

**Comment by lifei6671** [comment]
没发现这个问题啊。你看看这里 [http://doc.iminho.me/docs/scm](http://doc.iminho.me/docs/scm)。
你需要在nginx代理里面配置一个选项：
```
 proxy_set_header X-Forwarded-For $remote_addr;
 proxy_set_header Host            $http_host;
 proxy_set_header   X-Forwarded-Proto $scheme;
```

否则后台无法获取你访问的host信息。

**Comment by naokij** [comment]
好了，可以了。

顺便分享我的MinDoc的部署文件，包含Caddy跟systemd的设置
https://gist.github.com/naokij/260f0551729c74246c8b73fee680336e
Caddy是一个简单易用的web服务器，特色是自动设定好网站SSL证书
[Caddy官网](https://caddyserver.com/)
systemd是CentOS 7的启动管理程序
