### ISSUE TITLE
数据库结构升级

### ISSUE THREAD

**Issue by naokij** [lifei6671/godoc#45]
目前升级数据库结构使用`func mysqlUpdate() `，建议以后改成migration的方式，不然这个func会越来越复杂

**Comment by lifei6671** [comment]
不太明白。。

**Comment by naokij** [comment]
详见beego文档，[bee](https://beego.me/docs/install/bee.md)里面migrate命令
具体原理是，给数据库结构定义版本号，记录到数据库的一个表内，然后日后查询数据库结构版本来运行升级程序。
