### ISSUE TITLE
dev分支 管理后台->配置管理 无法打开

### ISSUE THREAD

**Issue by naokij** [lifei6671/godoc#46]
log显示·[E] [server.go:2568] template: manager/setting.tpl:84:61: executing "manager/setting.tpl" at <eq .ENABLE_DOCUMENT_...>: error calling eq: invalid type for comparison·
模版有问题

**Comment by lifei6671** [comment]
需要执行data/data.sql。因为新增了一个配置项，你的数据库没有。

**Comment by naokij** [comment]
可以了，谢谢。
