### ISSUE TITLE
must have one register DataBase alias named `default`

### ISSUE THREAD

**Issue by banneman** [lifei6671/godoc#56]
must have one register DataBase alias named `default`

**Comment by lifei6671** [comment]
请检查你的数据库配置是否正确。

**Comment by chasonyang** [comment]
修改 db_adapter=mysql|sqlite3 
二选一，如: db_adapter=mysql

**Comment by qetee** [comment]
这个问题是造成的原因应该是使用sqlite3时，  在使用sqlite3时，默认sqlite数据库的地址是： ./database/mindoc_db；  而默认项目里没有database这个目录；  当前mindoc并不会根据sqlite地址自动创建目录，从而导致因无法创建db文件而报出这个错误

解决方法： 在根目录下创建一个有读写权限的database目录后就ok了

**Comment by lifei6671** [comment]
@qetee 0.4版本已修复。
