### ISSUE TITLE
希望可执行程序增加参数解析flag，来设置根目录路径，配置文件路径等；

### ISSUE THREAD

**Issue by qetee** [lifei6671/godoc#59]
1. 希望可执行程序增加参数解析flag，来设置根目录路径，配置文件路径等； 比如：`mindoc --root="/path/to/mindoc" --config="/path/to/mindoc/app.conf"`; golang中进行参数读取还是很简单的，具体请参考标准库https://godoc.org/flag;   必须在项目根目录运行程序，才能正确读取项目静态文件，这有点傻傻的感觉；
2. 希望可执行程序增加daemon运行模式，以便于将可执行程序作为linux服务运行（可接受并处理signal）;b
 比如: `mindoc --daemon=true`; 可使用第三方库实现：https://github.com/takama/daemon；

**Comment by lifei6671** [comment]
1、项目使用的是beego框架，我只是实现了业务逻辑，您说的这些框架未实现，我也没办法实现。
2、这个可以使用第三方框架实现，比如supervisor。因用户运行的平台太复杂，因此这个项目暂时不考虑这个功能。

**Comment by lifei6671** [comment]
0.4版本已实现。
