### ISSUE TITLE
网站配置里面是否增加数据库备份和还原的指向呢。是否能挂在phpStudy里面呢？每次Windows里面需要一直开启godoc_windows_amd64.exe这个才能访问

### ISSUE THREAD

**Issue by gdlaoqiang** [lifei6671/godoc#60]

**Comment by gdlaoqiang** [comment]
或者这个应用程序可以做出QQ这样放在右下角也可以接受啊

**Comment by lifei6671** [comment]
phpStudy是PHP运行环境，和MinDoc无关。
数据库备份，如果是mysql，请使用第三方工具或MySQL自带的命令备份。如果是sqlite的话，拷贝出数据库文件即可。
后台运行，可以用vbs脚本配合cmd命令实现。
