### ISSUE TITLE
项目的文档管理：添加、删除、排序、重命名

### ISSUE THREAD

**Issue by grave01** [lifei6671/godoc#74]
只会新建文档，删除、排序、重命名这些操作要怎么完成，我没有找到。

**Comment by lifei6671** [comment]
我的项目->点击项目名称->设置

**Comment by grave01** [comment]
感谢回复。不是项目的管理，是项目里的文档。排序可以通过拖拽完成，但是重命名和删除不知道怎么弄。

**Comment by lifei6671** [comment]
靠尝试猜一下也应该之间是右键吧。

**Comment by grave01** [comment]
谷歌浏览器可以，但是火狐跟IE右键都是浏览器的选项。

**Comment by lifei6671** [comment]
我本地用火狐测试是正常的。你尝试刷新下页面，或看看是不是有脚本错误？

**Comment by grave01** [comment]
可以了，原来是我用了解除限制右键的脚本，停用掉就好了。
