### ISSUE TITLE
 windows 2008 下启动时报错

### ISSUE THREAD

**Issue by qiankunshe** [lifei6671/godoc#8]
github这个边不大会上传图片，我把错误内容放到git.oschina了
http://git.oschina.net/longfei6671/godoc/issues/3

**Comment by everyx** [comment]
和 #1 同样的问题

**Comment by lifei6671** [comment]
应该是编译的问题。我这没有server 2008，您可以尝试自己编译下。

**Comment by lifei6671** [comment]
试试v0.1.3中能执行不？

**Comment by qiankunshe** [comment]
明天我试试

**Comment by qiankunshe** [comment]
一样的错误，我今天有时间了，在本地编译试试

**Comment by lifei6671** [comment]
我知道是什么问题了，应该是时区的问题。我在程序中使用到了时区，而时区的配置文件是集成到Go的源码中的，没办法编译到程序中。

**Comment by qiankunshe** [comment]
那是不是安装的时候，要安装go环境？

**Comment by lifei6671** [comment]
如果不安装的话，就需要设置一个环境变量：ZONEINFO ，路径指向MinDoc跟目录下的/lib/time/zoneinfo.zip 文件
